import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import { execFile } from 'node:child_process';

const APP_DIR = path.join(process.env.PROGRAMDATA || 'C:\\ProgramData', 'GoDomain');
const CONFIG_PATH = path.join(APP_DIR, 'config.json');
const CADDYFILE_PATH = path.join(APP_DIR, 'Caddyfile');
const BACKUP_DIR = path.join(APP_DIR, 'backups');
const LOG_DIR = path.join(APP_DIR, 'logs');
const HOSTS_PATH = process.platform === 'win32'
  ? path.join(process.env.WINDIR || 'C:\\Windows', 'System32', 'drivers', 'etc', 'hosts')
  : '/etc/hosts';

const BEGIN = '# BEGIN GO-DOMAIN';
const END = '# END GO-DOMAIN';

function ensureDirs() {
  for (const dir of [APP_DIR, BACKUP_DIR, LOG_DIR]) fs.mkdirSync(dir, { recursive: true });
}

export function defaultConfig() {
  return {
    caddyPath: path.join(process.cwd(), 'caddy.exe'),
    aliases: [],
    lastAppliedAt: null
  };
}

export function readConfig() {
  ensureDirs();
  if (!fs.existsSync(CONFIG_PATH)) {
    const cfg = defaultConfig();
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(cfg, null, 2));
    return cfg;
  }
  return { ...defaultConfig(), ...JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')) };
}

export function writeConfig(config: any) {
  ensureDirs();
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function backupFile(filePath: string, label: string) {
  ensureDirs();
  if (!fs.existsSync(filePath)) return null;
  const backupPath = path.join(BACKUP_DIR, `${label}-${timestamp()}.bak`);
  fs.copyFileSync(filePath, backupPath);
  return backupPath;
}

export function normalizeDomain(domain: string) {
  return String(domain || '').trim().toLowerCase();
}

export function normalizeTarget(target: string) {
  return String(target || '').trim().replace(/^https?:\/\//, '').replace(/\/$/, '');
}

export function validateAlias(alias: any) {
  const domain = normalizeDomain(alias.domain);
  const target = normalizeTarget(alias.target);
  const domainRegex = /^[a-z0-9-]+(\.[a-z0-9-]+)+$/i;
  const targetRegex = /^([a-zA-Z0-9.-]+|\[[a-fA-F0-9:]+\]):\d{1,5}$/;

  if (!domainRegex.test(domain)) throw new Error('Domain harus seperti myapp.test atau api.localhost.');
  if (!targetRegex.test(target)) throw new Error('Target harus host:port, contoh localhost:3000 atau 192.168.1.50:8080.');

  const port = Number(target.split(':').pop());
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('Port target harus 1-65535.');

  return {
    id: alias.id || `${domain}-${Date.now()}`,
    domain,
    target,
    targetProtocol: alias.targetProtocol === 'https' ? 'https' : 'http',
    skipTlsVerify: Boolean(alias.skipTlsVerify),
    enabled: alias.enabled !== false
  };
}

function generateHostsBlock(aliases: any[]) {
  const domains = aliases.filter(a => a.enabled).map(a => a.domain).sort();
  return [BEGIN, ...domains.map(domain => `127.0.0.1 ${domain}`), END].join(os.EOL);
}

function updateHostsContent(original: string, aliases: any[]) {
  const block = generateHostsBlock(aliases);
  const escapedBegin = BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const escapedEnd = END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(`${escapedBegin}[\\s\\S]*?${escapedEnd}`, 'm');

  if (pattern.test(original)) return original.replace(pattern, block);
  return `${original.trimEnd()}${os.EOL}${os.EOL}${block}${os.EOL}`;
}

export const SUPPORTED_TLDS = [
  '.test', '.local', '.localhost', '.internal', '.example', '.invalid', '.lan',
  '.dev.local', '.app.local', '.site.local', '.project.local'
];

function isLocalDomain(domain: string) {
  return SUPPORTED_TLDS.some(tld => domain.endsWith(tld));
}

function generateCaddyfile(aliases: any[]) {
  const enabled = aliases.filter(a => a.enabled).sort((a, b) => a.domain.localeCompare(b.domain));
  const header = `# Generated by Go Domain. Do not edit this file manually.\n# Config path: ${CADDYFILE_PATH}\n\n`;
  return header + enabled.map(alias => {
    const upstream = `${alias.targetProtocol}://${alias.target}`;
    const tlsLine = isLocalDomain(alias.domain) ? '\n    tls internal' : '';
    if (alias.targetProtocol === 'https' && alias.skipTlsVerify) {
      return `${alias.domain} {${tlsLine}\n    reverse_proxy ${upstream} {\n        transport http {\n            tls_insecure_skip_verify\n        }\n    }\n}`;
    }
    return `${alias.domain} {${tlsLine}\n    reverse_proxy ${upstream}\n}`;
  }).join('\n\n') + '\n';
}

export function flushDns() {
  return new Promise(resolve => {
    if (process.platform !== 'win32') return resolve({ ok: true, output: 'Skipped: not Windows.' });
    execFile('ipconfig', ['/flushdns'], { windowsHide: true }, (error, stdout, stderr) => {
      resolve({ ok: !error, output: stdout || stderr || String(error || '') });
    });
  });
}

export function reloadCaddy() {
  const config = readConfig();
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(config.caddyPath)) return reject(new Error(`caddy.exe tidak ditemukan di ${config.caddyPath}.`));
    execFile(config.caddyPath, ['reload', '--config', CADDYFILE_PATH], { cwd: APP_DIR, windowsHide: true }, (error, stdout, stderr) => {
      if (error) return reject(new Error(stderr || stdout || error.message));
      resolve({ ok: true, message: stdout || 'Caddy reloaded.' });
    });
  });
}

export async function applyConfig(incomingConfig: any) {
  ensureDirs();
  const aliases = (incomingConfig.aliases || []).map(validateAlias);
  const config = { ...readConfig(), ...incomingConfig, aliases, lastAppliedAt: new Date().toISOString() };

  backupFile(HOSTS_PATH, 'hosts');
  backupFile(CADDYFILE_PATH, 'Caddyfile');

  const hostsOriginal = fs.existsSync(HOSTS_PATH) ? fs.readFileSync(HOSTS_PATH, 'utf8') : '';
  fs.writeFileSync(HOSTS_PATH, updateHostsContent(hostsOriginal, aliases));
  fs.writeFileSync(CADDYFILE_PATH, generateCaddyfile(aliases));
  writeConfig(config);

  const dns = await flushDns();
  try {
    await reloadCaddy();
  } catch (e) {
    // Ignore caddy reload failure, maybe caddy is not running
  }
  return { config, hostsPath: HOSTS_PATH, caddyfilePath: CADDYFILE_PATH, dns };
}

export function upsertAlias(alias: any) {
  const config = readConfig();
  const clean = validateAlias(alias);
  const exists = config.aliases.some((a: any) => a.id === clean.id || a.domain === clean.domain);
  config.aliases = exists
    ? config.aliases.map((a: any) => (a.id === clean.id || a.domain === clean.domain) ? { ...a, ...clean } : a)
    : [...config.aliases, clean];
  writeConfig(config);
  return config;
}

export function deleteAlias(idOrDomain: string) {
  const config = readConfig();
  config.aliases = config.aliases.filter((a: any) => a.id !== idOrDomain && a.domain !== idOrDomain);
  writeConfig(config);
  return config;
}
